spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.98.225:3306/user_rights
    username: enndfp
    password: Enndfp1218.
  # session 失效时间
  session:
    timeout: 86400 #一天


